[2025-07-28T13:13:56.423+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-28T13:13:56.445+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: carburant_etl_dag.transform_data manual__2025-07-28T13:13:51.030436+00:00 [queued]>
[2025-07-28T13:13:56.450+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: carburant_etl_dag.transform_data manual__2025-07-28T13:13:51.030436+00:00 [queued]>
[2025-07-28T13:13:56.450+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-07-28T13:13:56.459+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2025-07-28 13:13:51.030436+00:00
[2025-07-28T13:13:56.466+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=188) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-28T13:13:56.467+0000] {standard_task_runner.py:63} INFO - Started process 192 to run task
[2025-07-28T13:13:56.465+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'carburant_etl_dag', 'transform_data', 'manual__2025-07-28T13:13:51.030436+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etl_carburant.py', '--cfg-path', '/tmp/tmpyun31pao']
[2025-07-28T13:13:56.468+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask transform_data
[2025-07-28T13:13:56.481+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-28T13:13:56.506+0000] {task_command.py:426} INFO - Running <TaskInstance: carburant_etl_dag.transform_data manual__2025-07-28T13:13:51.030436+00:00 [running]> on host 695a2fdba44c
[2025-07-28T13:13:56.567+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='carburant_etl_dag' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-28T13:13:51.030436+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-28T13:13:51.030436+00:00'
[2025-07-28T13:13:56.568+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-28T13:13:56.577+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-28T13:13:56.793+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/transform/transform_data.py", line 9, in transform_xml
    tree = ET.parse(xml_path)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/xml/etree/ElementTree.py", line 1204, in parse
    tree.parse(source, parser)
  File "/usr/local/lib/python3.12/xml/etree/ElementTree.py", line 569, in parse
    self._root = parser._parse_whole(source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 2
[2025-07-28T13:13:56.801+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=carburant_etl_dag, task_id=transform_data, run_id=manual__2025-07-28T13:13:51.030436+00:00, execution_date=20250728T131351, start_date=20250728T131356, end_date=20250728T131356
[2025-07-28T13:13:56.806+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task transform_data (not well-formed (invalid token): line 1, column 2; 192)
[2025-07-28T13:13:56.851+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-28T13:13:56.864+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-28T13:13:56.865+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
